- name: Perform Language Setup
  hosts: boxknox
  become: yes
  tasks:
    - name: Install Golang
      import_tasks: golang.yml

    - name: Install python3
      import_tasks: python3.yml

    - name: Install python2
      import_tasks: python2.yml

    - name: Install Ruby and Gem
      import_tasks: ruby_and_gem.yml
